//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatto.BLL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusStringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusStringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chatto.BLL.StatusStringsResource", typeof(StatusStringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account removal failure..
        /// </summary>
        internal static string AccountRemoval_Failure {
            get {
                return ResourceManager.GetString("AccountRemoval_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account removed successfully!.
        /// </summary>
        internal static string AccountRemoval_OK {
            get {
                return ResourceManager.GetString("AccountRemoval_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add friend..
        /// </summary>
        internal static string AddFriend_AddFailure {
            get {
                return ResourceManager.GetString("AddFriend_AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding friend! (operation1).
        /// </summary>
        internal static string AddFriend_FailureOP1 {
            get {
                return ResourceManager.GetString("AddFriend_FailureOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding friend! (operation2).
        /// </summary>
        internal static string AddFriend_FailureOP2 {
            get {
                return ResourceManager.GetString("AddFriend_FailureOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added friend successfully!.
        /// </summary>
        internal static string AddFriend_OK {
            get {
                return ResourceManager.GetString("AddFriend_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add pending friend..
        /// </summary>
        internal static string AddPendingFriend_AddFailure {
            get {
                return ResourceManager.GetString("AddPendingFriend_AddFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding pending friend! (operation1).
        /// </summary>
        internal static string AddPendingFriend_FailureOP1 {
            get {
                return ResourceManager.GetString("AddPendingFriend_FailureOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while adding pending friend! (operation2).
        /// </summary>
        internal static string AddPendingFriend_FailureOP2 {
            get {
                return ResourceManager.GetString("AddPendingFriend_FailureOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added pending friend successfully!.
        /// </summary>
        internal static string AddPendingFriend_OK {
            get {
                return ResourceManager.GetString("AddPendingFriend_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect old password.
        /// </summary>
        internal static string ChangePassword_IncorrectOldPasswordError {
            get {
                return ResourceManager.GetString("ChangePassword_IncorrectOldPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed pass successfully!.
        /// </summary>
        internal static string ChangePassword_OK {
            get {
                return ResourceManager.GetString("ChangePassword_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and new passwords are same!.
        /// </summary>
        internal static string ChangePassword_SameOldNewPasswordError {
            get {
                return ResourceManager.GetString("ChangePassword_SameOldNewPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change failed!.
        /// </summary>
        internal static string ChangePassword_UpdateFailed {
            get {
                return ResourceManager.GetString("ChangePassword_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed!.
        /// </summary>
        internal static string ChangeSecondaryInfo_Failure {
            get {
                return ResourceManager.GetString("ChangeSecondaryInfo_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully!.
        /// </summary>
        internal static string ChangeSecondaryInfo_OK {
            get {
                return ResourceManager.GetString("ChangeSecondaryInfo_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not saved!.
        /// </summary>
        internal static string CreateMessage_Failure {
            get {
                return ResourceManager.GetString("CreateMessage_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was saved successfully!.
        /// </summary>
        internal static string CreateMessage_OK {
            get {
                return ResourceManager.GetString("CreateMessage_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend profile not found!.
        /// </summary>
        internal static string FriendNotFound {
            get {
                return ResourceManager.GetString("FriendNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration failed as Identity failed to create user..
        /// </summary>
        internal static string Registration_CreatingUserFailure {
            get {
                return ResourceManager.GetString("Registration_CreatingUserFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This User name already exists!.
        /// </summary>
        internal static string Registration_Failure {
            get {
                return ResourceManager.GetString("Registration_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration!.
        /// </summary>
        internal static string Registration_OK {
            get {
                return ResourceManager.GetString("Registration_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend entry not found in database!.
        /// </summary>
        internal static string RemoveFriend_DBEntryNotFound {
            get {
                return ResourceManager.GetString("RemoveFriend_DBEntryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while removing friend! (operation1).
        /// </summary>
        internal static string RemoveFriend_FailureOP1 {
            get {
                return ResourceManager.GetString("RemoveFriend_FailureOP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while removing friend! (operation2).
        /// </summary>
        internal static string RemoveFriend_FailureOP2 {
            get {
                return ResourceManager.GetString("RemoveFriend_FailureOP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed friend successfully!.
        /// </summary>
        internal static string RemoveFriend_OK {
            get {
                return ResourceManager.GetString("RemoveFriend_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend removal opreation failed..
        /// </summary>
        internal static string RemoveFriend_RemoveFailure {
            get {
                return ResourceManager.GetString("RemoveFriend_RemoveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was not removed!.
        /// </summary>
        internal static string RemoveMessage_Failure {
            get {
                return ResourceManager.GetString("RemoveMessage_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was removed!.
        /// </summary>
        internal static string RemoveMessage_OK {
            get {
                return ResourceManager.GetString("RemoveMessage_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while removing pending friend!.
        /// </summary>
        internal static string RemovePendingFriend_Failure {
            get {
                return ResourceManager.GetString("RemovePendingFriend_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed pending friend successfully!.
        /// </summary>
        internal static string RemovePendingFriend_OK {
            get {
                return ResourceManager.GetString("RemovePendingFriend_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile not found!.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
