//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chatto {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chatto.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has added you to their friendslist! Refreshing page....
        /// </summary>
        public static string Friend_AddedSuccessfullyNotification {
            get {
                return ResourceManager.GetString("Friend_AddedSuccessfullyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wants you to be their friend! Refreshing page....
        /// </summary>
        public static string Friend_PendingNotification {
            get {
                return ResourceManager.GetString("Friend_PendingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has removed you from their friendslist! Refreshing page....
        /// </summary>
        public static string Friend_RemovedSuccessfullyNotification {
            get {
                return ResourceManager.GetString("Friend_RemovedSuccessfullyNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has sent you a message!.
        /// </summary>
        public static string Message_ReceivedNotification {
            get {
                return ResourceManager.GetString("Message_ReceivedNotification", resourceCulture);
            }
        }
    }
}
